services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']

    Heptacom\HeptaConnect\Sdk\:
        resource: '../src/*'

    Heptacom\HeptaConnect\Sdk\Command\Install:
        arguments:
            - '%env(DATABASE_URL)%'
            - '%kernel.vendor_dir%'
            - '@cache.object'
            - '@monolog.logger'
            - '@Shopware\Core\Framework\DataAbstractionLayer\Indexing\EntityIndexerRegistry'
            - !tagged_iterator shopware.migration_source

    Heptacom\HeptaConnect\Sdk\Command\SelfUpdate:
        arguments:
            - '%kernel.vendor_dir%'

    Heptacom\HeptaConnect\Sdk\Command\PackageAdd:
        arguments:
            - '%kernel.vendor_dir%'

    Shopware\Core\Framework\Store\Services\OpenSSLVerifier:
        arguments:
            -
                - '%kernel.vendor_dir%/shopware/platform/src/Core/Framework/Store/public.key'
                - '%kernel.vendor_dir%/shopware/core/Framework/Store/public.key'

    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.vendor_dir%/../composer.json'
