services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Symfony\Component\Console\Command\Command:
            tags: ['console.command']

    Heptacom\HeptaConnect\Sdk\:
        resource: '../src/*'

    Heptacom\HeptaConnect\Sdk\Command\Install:
        arguments:
            - '%env(DATABASE_URL)%'
            - '%kernel.vendor_dir%'
            - !tagged_iterator shopware.migration_source

    Heptacom\HeptaConnect\Sdk\Command\SelfUpdate:
        arguments:
            - '%kernel.vendor_dir%'

    Heptacom\HeptaConnect\Sdk\Command\PackageAdd:
        arguments:
            - '%kernel.vendor_dir%'

    Heptacom\HeptaConnect\Sdk\Command\PackageInit:
        arguments:
            - '%kernel.vendor_dir%'

    Heptacom\HeptaConnect\Sdk\Command\Tinker:
        arguments:
            - '@Heptacom\HeptaConnect\Bridge\ShopwarePlatform\Support\AliasStorageKeyGenerator'
            - '@Heptacom\HeptaConnect\Core\Portal\PortalRegistry'
            - '@Heptacom\HeptaConnect\Core\StatusReporting\StatusReportingContextFactory'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\Listing\PortalNodeListActionInterface'
            - '@Heptacom\HeptaConnect\Storage\Base\Contract\Action\PortalNode\Get\PortalNodeGetActionInterface'

    Shopware\Core\Framework\Store\Services\OpenSSLVerifier:
        arguments:
            -
                - '%kernel.vendor_dir%/shopware/platform/src/Core/Framework/Store/public.key'
                - '%kernel.vendor_dir%/shopware/core/Framework/Store/public.key'

    Heptacom\HeptaConnect\Core\Component\Composer\PackageConfigurationLoader:
        arguments:
            - '%kernel.vendor_dir%/../composer.json'
            - '@cache.system'

    Shopware\Core\Framework\Plugin\PluginService:
        arguments:
            - '%kernel.plugin_dir%'
            - '%kernel.vendor_dir%/../'
            - '@plugin.repository'
            - '@language.repository'
            - '@Shopware\Core\Framework\Plugin\Changelog\ChangelogService'
            - '@Shopware\Core\Framework\Plugin\Util\PluginFinder'
            - '@Shopware\Core\Framework\Plugin\Util\VersionSanitizer'

    Shopware\Core\Framework\Plugin\Requirement\RequirementsValidator:
        arguments:
            - '@plugin.repository'
            - '%kernel.vendor_dir%/../'
